// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gbugdqytlenwhwsflcek.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdidWdkcXl0bGVud2h3c2ZsY2VrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEwNjI0MTIsImV4cCI6MjA4NjYzODQxMn0.vcq7W6VqW3WZj1PtkEInTmC0H6Zgl6qTjMbYsfNGST8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});